version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:803871049728:task-definition/myapp-task:1"
        LoadBalancerInfo:
          ContainerName: "myapp-container"
          ContainerPort: 3000